"""create users table

Revision ID: d0d2de42a85e
Revises: c7fba5dabd37
Create Date: 2025-05-08 12:28:58.541827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d2de42a85e'
down_revision: Union[str, None] = 'c7fba5dabd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=10), nullable=False))
    op.add_column('users', sa.Column('regular_player', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'regular_player')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
